### ISSUE TITLE
Unsuccessful TensorSliceReader constructor

### ISSUE THREAD

**Issue by iiapache** [brightmart/xlnet_zh#10]
预训练脚本：

python $SCRIPT_DIR/run_classifier.py \
    --spiece_model_file=${XLNET_DIR}/spiece.model \
    --model_config_path=${XLNET_DIR}/xlnet_config.json \
    --init_checkpoint=${XLNET_DIR}/xlnet_model.ckpt \

加载模型碰到问题：
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /data/user0/test/classifier/bin/xlnet/data//xlnet_model.ckpt
Traceback (most recent call last):
  File "/data/user0/test/classifier/bin/xlnet//run_classifier.py", line 1103, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/data/user0/test/classifier/bin/xlnet//run_classifier.py", line 971, in main
    estimator.train(input_fn=train_input_fn, max_steps=train_steps)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1122, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1254, in _actual_train_model_distributed
    self.config))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1199, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 641, in _call_for_each_replica
    return _call_for_each_replica(self._container_strategy(), fn, args, kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 852, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/data/user0/test/classifier/bin/xlnet//run_classifier.py", line 750, in model_fn
    scaffold_fn = model_utils.init_from_checkpoint(FLAGS)
  File "/data/user0/test/classifier/bin/xlnet/model_utils.py", line 88, in init_from_checkpoint
    ) = get_assignment_map_from_checkpoint(tvars, init_checkpoint)
  File "/data/user0/test/classifier/bin/xlnet/model_utils.py", line 293, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 95, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 64, in load_checkpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /data/user0/test/classifier/bin/xlnet/data//xlnet_model.ckpt

**Comment by liuziyi219** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by iiapache** [comment]
> 我也遇到了同样的问题，请问你解决了吗

我是因为init_checkpoint路径中多了个“/”导致的，去掉就ok了，且init_checkpoint最好用绝对路径，相对路径好像需要用当前目录“./”或上级目录“../”指定

**Comment by liuziyi219** [comment]
> > 我也遇到了同样的问题，请问你解决了吗
> 
> 我是因为init_checkpoint路径中多了个“/”导致的，去掉就ok了，且init_checkpoint最好用绝对路径，相对路径好像需要用当前目录“./”或上级目录“../”指定

谢谢，你下载的模型里是有xlnet_modal.cpkt吗，我的只有xlnet_modal.cpkt.meta, xlnet_modal.cpkt.index这些，直接写xlnet_modal.cpkt就可以吗
